### PR TITLE
send the correct Host header when using -o url

### LINKED ISSUE #161: GovCloud Redirection Is Broken
Some recent code change (that didn't change the S3FS version from 1.78) has broken GovCloud redirection.  Specifically:

We have a number of Ubuntu GovCloud instances.  We use a standardized document to pull S3FS and compile it when installing to a new instance.

We compile and install with the following procedure:

-----

Install S3FS

Install Development Packages

Compiling S3FS requires a number of development packages to be installed.  To do so, as a non-root user, enter the following command.

Be aware that line breaks are a function of the word processor.  The command should be entered on a single line:

sudo apt-get install build-essential git libfuse-dev libcurl4-openssl-dev libxml2-dev mime-support automake libtool pkg-config libssl-dev

Obtain S3FS Source Code

To compile from source, you must obtain the S3FS source code using git to clone a copy from GitHub.

To do so, enter the following command: 

git clone https://github.com/s3fs-fuse/s3fs-fuse

Compile the Source Code

To compile the S3FS source code, as a non-root user, enter the commands:

cd s3fs-fuse/
./autogen.sh
./configure --prefix=/usr --with-openssl
make

Install the Compiled Binary Executable

To install the compiled executable file, enter the command:

sudo make install

Test the Installation

To test that S3FS was installed correctly, enter the following command:

	s3fs --version

This should return text similar to:

Amazon Simple Storage Service File System V1.78 with OpenSSL
Copyright (C) 2010 Randy Rizun rrizun@gmail.com
License GPL2: GNU GPL version 2 http://gnu.org/licenses/gpl.html
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

-----

This procedure has not changed since 16 January 2015 when I wrote it.  Over the last several months, we have spun up multiple instances in GovCloud using this procedure.

When using a binary compiled on 16 January, we can successfully mount a GovCloud bucket via redirection.  I.e. our standard /etc/fstab entry:

s3fs#prd.project.files        /java_data/s3projects   fuse    allow_other,host=http://s3-us-gov-west-1.amazonaws.com     0 0

When using a binary compiled this morning, this mount fails.  Specifically:

-----

ubuntu@govs3fstest:~$ sudo s3fs -f -d -o url=http://s3-us-gov-west-1.amazonaws.com -o multireq_max=5 -o allow_other -o endpoint=us-gov-west-1 -o passwd_file=/etc/passwd-s3fs uat.project.files /mnt2
    set_moutpoint_attribute(3530): PROC(uid=0, gid=0) - MountPoint(uid=0, gid=0, mode=40755)
s3fs_init(2713): init
s3fs_check_service(3070): check services.
    CheckBucket(2538): check a bucket.
    RequestPerform(1584): connecting to URL http://uat.project.files.s3-us-gov-west-1.amazonaws.com/
    RequestPerform(1600): HTTP response code 404
    RequestPerform(1624): HTTP response code 404 was returned, returning ENOENT
CheckBucket(2590): Check bucket failed, S3 response: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message><BucketName>uat.project.files.s3.amazonaws.com</BucketName><RequestId>D38F80FDA23C32AB</RequestId><HostId>Olwju4mzZcyQJL8RWwa+4YeSzdM+NUtI+TaYezvAKEEIKc/Em18cdPACYYIPDyJQ</HostId></Error>
s3fs: bucket not found

-----

And:

-----

ubuntu@govs3fstest:~$ sudo s3fs -f -d -o url=http://s3-us-gov-west-1.amazonaws.com -o multireq_max=5 -o allow_other -o passwd_file=/etc/passwd-s3fs uat.project.files /mnt2
    set_moutpoint_attribute(3530): PROC(uid=0, gid=0) - MountPoint(uid=0, gid=0, mode=40755)
s3fs_init(2713): init
s3fs_check_service(3070): check services.
    CheckBucket(2538): check a bucket.
    RequestPerform(1584): connecting to URL http://uat.project.files.s3-us-gov-west-1.amazonaws.com/
    RequestPerform(1600): HTTP response code 400
    RequestPerform(1614): HTTP response code 400 was returned, returing EIO.
CheckBucket(2590): Check bucket failed, S3 response: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AuthorizationHeaderMalformed</Code><Message>The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'us-gov-west-1'</Message><Region>us-gov-west-1</Region><RequestId>40C446F54F56D3E7</RequestId><HostId>ERxUtFprPYGv7rgJPFEvpMFHWA4rlqDrO9xYu6PQT8PxZQN3Xs3OVoXILPwuk3GY</HostId></Error>
s3fs_check_service(3103): Could not connect wrong region us-east-1, so retry to connect region us-gov-west-1.
    CheckBucket(2538): check a bucket.
    RequestPerform(1584): connecting to URL http://uat.project.files.s3-us-gov-west-1.amazonaws.com/
    RequestPerform(1600): HTTP response code 404
    RequestPerform(1624): HTTP response code 404 was returned, returning ENOENT
CheckBucket(2590): Check bucket failed, S3 response: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message><BucketName>uat.project.files.s3.amazonaws.com</BucketName><RequestId>800D0F152C6D7F28</RequestId><HostId>IHmeo4jc0x5tStIF3kmYGKpnvJC1odFITl+x/58sbLOIQ9iGX061qQ/Zq16csOYt</HostId></Error>
s3fs: bucket not found

-----

Clearly, with the current code, it is not correctly redirecting to the GovCloud S3 platform in spite of being explicitly told to redirect there.

Interestingly, there is a significant difference in the compiled binaries.  In the following listing, the today-compiled binary is the ".old" file.  The plain "s3fs" is a January compile that was copied from a production system.

-----

root@govs3fs:/usr/bin# ls -al s3fs*
-rwxr-xr-x 1 root root 3592580 Mar 31 14:12 s3fs
-rwxr-xr-x 1 root root 4020379 Mar 31 13:57 s3fs.org

-----

The first (January-compiled) binary works.  The second (today-compiled) does not.

I would be happy to provide additional information if it's needed.

### PR DESCRIPTION
**Pull request by kahing**
fixes #161

### CODE REVIEW

File: src/curl.cpp [hunk 1]
```diff
@@ -92,6 +94,36 @@ static bool make_md5_from_string(const char* pstr, string& md5)
...
+        host = url.substr(http.size());
+    } else if (url.compare(0, https.size(), https) == 0) {
+        host = url.substr(https.size());
+    } else {
+        assert(!"url does not begin with http:// or https://");
+    }
+
+    size_t idx;
+
+    if ((idx = host.find(':')) != string::npos || (idx = host.find('/')) != string::npos) {
```
Comment (andrewgaul) [inline src/curl.cpp]: `host.find_first_of(":/")` ?

**Comment by andrewgaul** [comment]
:+1:
